#Xiaoxuan Wang
#HW2
```{r}
#uniform random number generator

ran2 <- function(seed,n=1){
  IM1<- 2147483563 
  IM2<- 2147483399
  AM<- (1.0/IM1) 
  IMM1<- (IM1-1)
  IA1<- 40014 
  IA2<- 40692
  IQ1<- 53668 
  IQ2<- 52774 
  IR1<- 12211 
  IR2<- 3791 
  NTAB<- 32
  NDIV<- (1+IMM1/NTAB) 
  EPS<- 1.2e-7 
  RNMX<- (1.0-EPS)
  idum<-seed
  idum2<- 123456789
  iy<- 0
  iv<- rep(0,NTAB)

  random<-rep(0,n)
  for(i in 1:n){
    if(idum<=0){
      idum<- max(-idum,1)
      idum2=idum
      j<-NTAB+8
      while(j>0){
        k=as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if(idum<0) {idum = idum + IM1}
        if(j <= NTAB) {iv[j] <- idum}
        j<- j-1
      }
      iy=iv[1]
    }
    k=as.integer(idum/IQ1)
    idum=IA1*(idum-k*IQ1)-k*IR1
    if(idum<0) {idum = idum + IM1}
    k=as.integer(idum2/IQ2)
    idum2=IA2*(idum2-k*IQ2)-k*IR2
    if(idum2<0) {idum2 = idum2 + IM2}
    j=as.integer(iy/NDIV)+1
    iy=iv[j]-idum2
    iv[j] = idum
    if(iy<1) {iy = iy + IMM1}
    if(AM*iy<RNMX){random[i]<-AM*iy}
    else {random[i]<-RNMX}
  }
  return(random)
}
  
  
```

```{r}
#normal random number generator
invnor<- function(uni){
  a0=2.50662823884
  a1=-18.61500062529
  a2=41.39119773534
  a3=-25.44106049637
  b0=-8.47351093090
  b1=23.08336743743
  b2=-21.06224101826
  b3=3.13082909833
  c0=0.3374754822726147
  c1=0.9761690190917186
  c2=0.1607979714918209
  c3=0.0276438810333863
  c4=0.0038405729373609
  c5=0.0003951896511919
  c6=0.0000321767881768
  c7=0.0000002888167364
  c8=0.0000003960315187

  
  invnor<-rep(0,length(uni))
  for(i in 1:length(invnor)){
    y=uni[i]-0.5
    if(abs(y)<0.42){
      r<-y*y
      x<-y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else{
      r<-uni[i]
      if(y>0) r<- 1-uni[i]
      r<- log(-log(r))
      x<- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0) x<- -x
    }
    invnor[i]<- x
  }
  return(invnor)
}
```

```{r}
#1000 paths
seed<- 0
n<- 1000000
u<-ran2(seed,n)
norm_c<-invnor(u)

S0<- 100
rf<- 0.03
vol<-0.25
T<- 1
delta_t<- T/12

numpath<- 1000
K<-S0
ST_Vals<-matrix(rep(0),nrow=12,ncol=numpath)
M<-matrix(rep(0), numpath)
m<-matrix(rep(0), numpath)

jcount<-1
lcount<-1
while(jcount<=numpath){
  St<-S0
  for(kcount in 1:12){
    St<-St*(exp((rf-0.5*(vol^2))*delta_t+vol*sqrt(delta_t)*norm_c[lcount]))
    ST_Vals[kcount,jcount]<-St
    lcount<-lcount+1
  }
  jcount=jcount+1
}

M<-apply(ST_Vals,2,max)
m<-apply(ST_Vals,2,min)

payoff1<- M-ST_Vals[12,]
payoff1[payoff1<0]=0 
#price of the option with a payoff of {max(s1,s2,...,sT)-sT}+
P1<-exp(-rf*T)*mean(payoff1) 

payoff2<-ST_Vals[12,]-m
payoff2[payoff2<0]=0
#price of the option with a payoff of {sT-min(s1,s2,...,sT)}+
P2<-exp(-rf*T)*mean(payoff2) 

P1
print('CI:')
c(P1-1.645*sd(payoff1*exp(-rf*T))/sqrt(numpath),P1+1.645*sd(payoff1*exp(-rf*T))/sqrt(numpath)) #CI

P2
print("CI:")
c(P2-1.645*sd(payoff2*exp(-rf*T))/sqrt(numpath),P2+1.645*sd(payoff2*exp(-rf*T))/sqrt(numpath)) #CI

```
```{r}
#10000 paths
seed<- 0
n<- 1000000
u<-ran2(seed,n)
norm_c<-invnor(u)

S0<- 100
rf<- 0.03
vol<-0.25
T<- 1
delta_t<- T/12

numpath<- 10000
K<-S0
ST_Vals<-matrix(rep(0),nrow=12,ncol=numpath)
M<-matrix(rep(0), numpath)
m<-matrix(rep(0), numpath)

jcount<-1
lcount<-1
while(jcount<=numpath){
  St<-S0
  for(kcount in 1:12){
    St<-St*(exp((rf-0.5*(vol^2))*delta_t+vol*sqrt(delta_t)*norm_c[lcount]))
    ST_Vals[kcount,jcount]<-St
    lcount<-lcount+1
  }
  jcount=jcount+1
}

M<-apply(ST_Vals,2,max)
m<-apply(ST_Vals,2,min)

payoff1<- M-ST_Vals[12,] 
payoff1[payoff1<0]=0 
#price of the option with a payoff of {max(s1,s2,...,sT)-sT}+
P1_10000<-exp(-rf*T)*mean(payoff1) 

payoff2<-ST_Vals[12,]-m
payoff2[payoff2<0]=0
#price of the option with a payoff of {sT-min(s1,s2,...,sT)}+
P2_10000<-exp(-rf*T)*mean(payoff2) 

P1_10000
print('CI:')
c(P1_10000-1.645*sd(payoff1*exp(-rf*T))/sqrt(numpath),P1_10000+1.645*sd(payoff1*exp(-rf*T))/sqrt(numpath)) #CI

P2_10000
print("CI:")
c(P2_10000-1.645*sd(payoff2*exp(-rf*T))/sqrt(numpath),P2_10000+1.645*sd(payoff2*exp(-rf*T))/sqrt(numpath)) #CI
```
As the number of paths increases, the confidence interval tends
to concentrate


```{r}
#1000 paths for Quantos
getSymbols("EUR/USD", from = "2019-01-04", to = "2019-04-04",src="oanda") 
getSymbols("AAPL",from = "2019-01-04", to = "2019-04-04",src="yahoo")
AAPL=AAPL[,6]
test<-merge.xts(AAPL,EURUSD,join='inner')
AAPL=as.matrix(test[,1]) #AAPL price series
E_U<-as.matrix(test[,2])
E_U<-1/E_U

seed<-0
numran<-500000
u<-ran2(seed,numran)
norm1<-invnor(u)

seed<-1000
numran<-500000
u<-ran2(seed,numran)
norm2<-invnor(u)


S0=AAPL[length(AAPL)]
rUSD<-0.024
T<-3/12

n<-length(AAPL)
rets1<-rep(0,n-1)
for(i in 1:n-1){rets1[i] = log(AAPL[i+1]/AAPL[i])}
VolStock<-sd(rets1)*sqrt(251)

FX0<- E_U[length(E_U)]
rFX<- -0.00563334

n<-length(E_U)
rets2<-rep(0,n-1)
for(i in 1:n-1){rets2[i] = log(E_U[i+1]/E_U[i])}
VolFX<-sd(rets2)*sqrt(251)

KFX<-S0*FX0

rho<-cor(rets1,rets2)

eps1<-norm1
eps2<-rho*norm1+(sqrt(1-rho^2))*norm2

numpath<-1000
ST_Vals<-c(rep(0,numpath))
ST_Rets<-c(rep(0,numpath))
FX_Vals<-c(rep(0,numpath))
FX_Rets<-c(rep(0,numpath))
Quanto_Vals<-c(rep(0,numpath))
jcount<-1
while(jcount<=numpath){
  ST<-S0*(exp((rUSD-0.5*(VolStock^2))*T+VolStock*sqrt(T)*eps1[jcount]))
  ST_Vals[jcount]<-ST
  FX<-FX0*(exp((rFX-rUSD-0.5*(VolFX^2))*T+VolFX*sqrt(T)*eps2[jcount]))
  FX_Vals[jcount]<-FX
  Quanto<-max(ST*FX-KFX,0)
  Quanto_Vals[jcount]<-Quanto
  jcount=jcount+1
}

P_1000<- mean(Quanto_Vals*exp(-rFX*T))
sigma<-sd(Quanto_Vals*exp(-rFX*T))
CI_1000<-c(P_1000-1.645*sigma/sqrt(numpath),P_1000+1.645*sigma/sqrt(numpath))

P_1000 #Quantos price
CI_1000 #Confidence Interval
```
```{r}
#10000 paths for Quantos
numpath<-10000
ST_Vals<-c(rep(0,numpath))
ST_Rets<-c(rep(0,numpath))
FX_Vals<-c(rep(0,numpath))
FX_Rets<-c(rep(0,numpath))
Quanto_Vals<-c(rep(0,numpath))
jcount<-1
while(jcount<=numpath){
  ST<-S0*(exp((rUSD-0.5*(VolStock^2))*T+VolStock*sqrt(T)*eps1[jcount]))
  ST_Vals[jcount]<-ST
  ST_Rets[jcount]<-log(ST_Vals[jcount]/S0)
  FX<-FX0*(exp((rFX-rUSD-0.5*(VolFX^2))*T+VolFX*sqrt(T)*eps2[jcount]))
  FX_Vals[jcount]<-FX
  FX_Rets[jcount]<-log(FX_Vals[jcount]/FX0)
  Quanto<-max(ST*FX-KFX,0)
  Quanto_Vals[jcount]<-Quanto
  jcount=jcount+1
}


P_10000<- mean(Quanto_Vals*exp(-rFX*T))
sigma<-sd(Quanto_Vals*exp(-rFX*T))
CI_10000<-c(P_10000-1.645*sigma/sqrt(numpath),P_10000+1.645*sigma/sqrt(numpath))

P_10000 #Quantos price
CI_10000 #Confidence Interval
```


