#Xiaoxuan_Wang
#ASSIGNMENT_3
#xwang398@fordham.edu

#1
```{r}
#uniform random number generator
ran2 <- function(seed,n=1){
  IM1<- 2147483563 
  IM2<- 2147483399
  AM<- (1.0/IM1) 
  IMM1<- (IM1-1)
  IA1<- 40014 
  IA2<- 40692
  IQ1<- 53668 
  IQ2<- 52774 
  IR1<- 12211 
  IR2<- 3791 
  NTAB<- 32
  NDIV<- (1+IMM1/NTAB) 
  EPS<- 1.2e-7 
  RNMX<- (1.0-EPS)
  idum<-seed
  idum2<- 123456789
  iy<- 0
  iv<- rep(0,NTAB)

  random<-rep(0,n)
  for(i in 1:n){
    if(idum<=0){
      idum<- max(-idum,1)
      idum2=idum
      j<-NTAB+8
      while(j>0){
        k=as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if(idum<0) {idum = idum + IM1}
        if(j <= NTAB) {iv[j] <- idum}
        j<- j-1
      }
      iy=iv[1]
    }
    k=as.integer(idum/IQ1)
    idum=IA1*(idum-k*IQ1)-k*IR1
    if(idum<0) {idum = idum + IM1}
    k=as.integer(idum2/IQ2)
    idum2=IA2*(idum2-k*IQ2)-k*IR2
    if(idum2<0) {idum2 = idum2 + IM2}
    j=as.integer(iy/NDIV)+1
    iy=iv[j]-idum2
    iv[j] = idum
    if(iy<1) {iy = iy + IMM1}
    if(AM*iy<RNMX){random[i]<-AM*iy}
    else {random[i]<-RNMX}
  }
  return(random)
}
```


```{r}
#normal random number generator
invnor<- function(uni){
  a0=2.50662823884
  a1=-18.61500062529
  a2=41.39119773534
  a3=-25.44106049637
  b0=-8.47351093090
  b1=23.08336743743
  b2=-21.06224101826
  b3=3.13082909833
  c0=0.3374754822726147
  c1=0.9761690190917186
  c2=0.1607979714918209
  c3=0.0276438810333863
  c4=0.0038405729373609
  c5=0.0003951896511919
  c6=0.0000321767881768
  c7=0.0000002888167364
  c8=0.0000003960315187

  
  invnor<-rep(0,length(uni))
  for(i in 1:length(invnor)){
    y=uni[i]-0.5
    if(abs(y)<0.42){
      r<-y*y
      x<-y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else{
      r<-uni[i]
      if(y>0) r<- 1-uni[i]
      r<- log(-log(r))
      x<- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0) x<- -x
    }
    invnor[i]<- x
  }
  return(invnor)
}
```

```{r}
seed<- -10
u<-ran2(seed, 200000)
norm<-invnor(u) #generate a series of normal-distributed random variables

```


```{r}

#stock prices paths with miu=0.08, sigma=0.2

miu<-0.08
sigma<-0.2
numpath<-10000
T<-1
dt<-1/12
S0<-100
count<-1
ncount<-1
stock_prices<-matrix(rep(100),nrow=13,ncol=numpath)
while(count<numpath){
  St<-S0
  for (i in 2:13) {
    St<-St*exp(miu*dt+sigma*sqrt(dt)*norm[ncount])
    stock_prices[i,count]<-St
    ncount<- ncount+1
  }
  count= count+1
}

S13s<-stock_prices[13,]

assumption_mean<-exp(miu+sigma*sigma/2)-1
sample_mean<-mean(S13s/100-1)

assumption_std<-exp(miu)*sqrt(exp(sigma*sigma)-1)
sample_std<-sd(S13s/100-1)

#The sample mean and standard deviation of the sample returns is close to that under the assumption of miu=0.08 and sigma=0.2
c(assumption_mean, sample_mean) 
c(assumption_std, sample_std)

```

```{r}
#Black-Scholes Put Option Price
BS_P<-function(S,K,vol,t,r){
  d1=(log(S/K)+(r+0.5*vol*vol)*t)/(vol*sqrt(t))
  d2=d1-vol*sqrt(t)
  P = K*exp(-r*t)*pnorm(-d2)-S*pnorm(-d1)
  return(P)
}
```


```{r}
#miu=0.08, sigma=0.2, K=1.05*S
S0<-100
K<-1.05 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=1.05*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return<-rep(0,8)
std_return<-rep(0,8)
mean_return[1]=mean(payoffs_T)#miu=0.08, sigma=0.2, K=1.05*S
std_return[1]=sd(payoffs_T)
```

```{r}
#miu=0.08, sigma=0.2, K=0.95*S
S0<-100
K<-0.95 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=0.95*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[2]=mean(payoffs_T)#miu=0.08, sigma=0.2, K=0.95*S
std_return[2]=sd(payoffs_T)
```

```{r}
#stock prices paths with miu=0.12, sigma=0.3

miu<-0.12
sigma<-0.3
numpath<-10000
T<-1
dt<-1/12
S0<-100
count<-1
ncount<-1
stock_prices<-matrix(rep(100),nrow=13,ncol=numpath)
while(count<numpath){
  St<-S0
  for (i in 2:13) {
    St<-St*exp(miu*dt+sigma*sqrt(dt)*norm[ncount])
    stock_prices[i,count]<-St
    ncount<- ncount+1
  }
  count= count+1
}

S13s<-stock_prices[13,]

assumption_mean<-exp(miu+sigma*sigma/2)-1
sample_mean<-mean(S13s/100-1)

assumption_std<-exp(miu)*sqrt(exp(sigma*sigma)-1)
sample_std<-sd(S13s/100-1)

#The sample mean and standard deviation of the sample returns is close to that under the assumption of miu=0.12 and sigma=0.3
c(assumption_mean, sample_mean) 
c(assumption_std, sample_std)

```

```{r}
#miu=0.12, sigma=0.3, K=1.05*S
S0<-100
K<-1.05 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=1.05*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[3]=mean(payoffs_T)#miu=0.12, sigma=0.3, K=1.05*S
std_return[3]=sd(payoffs_T)
```

```{r}
#miu=0.12, sigma=0.3, K=0.95*S
S0<-100
K<-0.95 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=0.95*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[4]=mean(payoffs_T)#miu=0.12, sigma=0.3, K=0.95*S
std_return[4]=sd(payoffs_T)
```


```{r}
#stock prices paths with miu=0.08, sigma=0.3
miu<-0.08
sigma<-0.3
numpath<-10000
T<-1
dt<-1/12
S0<-100
count<-1
ncount<-1
stock_prices<-matrix(rep(100),nrow=13,ncol=numpath)
while(count<numpath){
  St<-S0
  for (i in 2:13) {
    St<-St*exp(miu*dt+sigma*sqrt(dt)*norm[ncount])
    stock_prices[i,count]<-St
    ncount<- ncount+1
  }
  count= count+1
}

S13s<-stock_prices[13,]

assumption_mean<-exp(miu+sigma*sigma/2)-1
sample_mean<-mean(S13s/100-1)

assumption_std<-exp(miu)*sqrt(exp(sigma*sigma)-1)
sample_std<-sd(S13s/100-1)

#The sample mean and standard deviation of the sample returns is close to that under the assumption of miu=0.08 and sigma=0.3
c(assumption_mean, sample_mean) 
c(assumption_std, sample_std)

```

```{r}
#miu=0.08, sigma=0.3, K=1.05*S
S0<-100
K<-1.05 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=1.05*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[5]=mean(payoffs_T)#miu=0.08, sigma=0.3, K=1.05*S
std_return[5]=sd(payoffs_T)
```

```{r}
#miu=0.08, sigma=0.3, K=0.95*S
S0<-100
K<-0.95 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=0.95*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[6]=mean(payoffs_T)#miu=0.08, sigma=0.3, K=0.95*S
std_return[6]=sd(payoffs_T)
```

```{r}
#stock prices paths with miu=0.12, sigma=0.2

miu<-0.12
sigma<-0.2
numpath<-10000
T<-1
dt<-1/12
S0<-100
count<-1
ncount<-1
stock_prices<-matrix(rep(100),nrow=13,ncol=numpath)
while(count<numpath){
  St<-S0
  for (i in 2:13) {
    St<-St*exp(miu*dt+sigma*sqrt(dt)*norm[ncount])
    stock_prices[i,count]<-St
    ncount<- ncount+1
  }
  count= count+1
}

S13s<-stock_prices[13,]

assumption_mean<-exp(miu+sigma*sigma/2)-1
sample_mean<-mean(S13s/100-1)

assumption_std<-exp(miu)*sqrt(exp(sigma*sigma)-1)
sample_std<-sd(S13s/100-1)

#The sample mean and standard deviation of the sample returns is close to that under the assumption of miu=0.12 and sigma=0.2
c(assumption_mean, sample_mean) 
c(assumption_std, sample_std)

```

```{r}
#miu=0.12, sigma=0.2, K=1.05*S
S0<-100
K<-1.05 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=1.05*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=1.05*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[7]=mean(payoffs_T)#miu=0.12, sigma=0.2, K=1.05*S
std_return[7]=sd(payoffs_T)
```

```{r}
#miu=0.12, sigma=0.2, K=0.95*S
S0<-100
K<-0.95 * S0
vol<-sigma
r<-0.02
payoffs_T<-rep(0,numpath)

for(i in 1:numpath){
  rollin<- -BS_P(S0,K,vol,t=3/12,r)#at time t=0
  payoffs_T[i]= payoffs_T[i]+rollin*exp(r*1) 
  for(j in 2:12){
    rollin = -BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j,i],vol,t=3/12,r)
    rollout= BS_P(S=stock_prices[j,i],K=0.95*stock_prices[j-1,i],vol,t=2/12,r)
    payoffs_T[i]=payoffs_T[i] + (rollin+rollout)*exp(r*(1-(j-1)/12))
  }
  rollout=BS_P(S=stock_prices[13,i],K=0.95*stock_prices[12,i],vol,t=2/12,r)
  payoffs_T[i]=payoffs_T[i] + rollout
}
payoffs_T=payoffs_T+S13s-rep(100,numpath)

mean_return[8]=mean(payoffs_T)#miu=0.12, sigma=0.2, K=0.95*S
std_return[8]=sd(payoffs_T)
```

```{r}
test<-t(matrix(c(mean_return,std_return),nrow = 8))
table<-as.table(test)
row.names(table)=c("mean of rets","std of rets")
colnames(table)<-c("0.08/0.2/105","0.08/0.2/95","0.12/0.3/105","0.12/0.3/95","0.08/0.3/105","0.08/0.3/95","0.12/0.2/105","0.12/0.2/95")
table
```

Given a certain drift(0.08 or 0.12) and a certain strike(105% or 95%), the higher the volatility, the higher the mean and standard deviation of the return.
Given a certain drift(0.08 or 0.12) and a certain volatility(0.2 or 0.3), using the out-of-money put option strategy has a higher mean and standard deviation of return.

#2
```{r}
op_price=function(rf,t,K,S,vol){
  count<-1
  numran<-10000
  Option<-rep(0,numran)
while(count<=numran){
  ST<-S*(exp((rf-0.5*(vol^2))*t+vol*sqrt(t)*norm[count]))
  Payoff<- ST-K
  if(Payoff>0) {
    Option[count]<-Payoff
  }
  count = count +1       
}
return(mean(exp(-rf*t)*Option))
}
  
```

```{r}
#date: 2017/09/01
#expiration: 2019/1/18
#Time to M: 504days
X <- read.csv(file="/Users/xuan/Desktop/Simulation/HW/HW3/data.csv", header=TRUE, sep=",")
Ks<-X[,1]/1000
prices<-X[,2]
S<-172.02 #spot price
t=504/365
rf=0.0261 #risk-free rate

implied_vol=c()
for(i in 1:length(Ks)){
  K=Ks[i]
  price=prices[i]
  implied_vol[i]=uniroot(function(x) op_price(rf,t,K,S,x)-price,c(0,1))
}
plot(Ks,implied_vol)
```
#3
```{r}
r=c(0.01,0.02,0.025,0.03,0.0325)
p=0
for(i in 1:5){
  p=p+6*exp(-r[i]*i)
  if(i==5){p=p+100*exp(-r[i]*i)}
}

f=rep(r[1], length(r))
for(i in 2:5){
  f[i]=r[i]*(i)-r[i-1]*(i-1)
}
```

```{r}
numpaths<-10000
Maturity<-5
sim_r<-matrix(rep(0),nrow=Maturity, ncol=numpaths)
sim_bond<-matrix(rep(0),nrow=Maturity+1, ncol=numpaths)
jcount<-1
kcount<-1
ncount<-1
DeltaT<-1
rshort<-r[1]
Volatility<-0.02
for (kcount in 1:numpaths) {
  rshort<-r[1]
  sim_r[1,kcount]<-rshort
  for(jcount in 2:5){
    rshort<-rshort+(f[jcount]-f[jcount-1])+(0.5*Volatility^2)*DeltaT+Volatility*sqrt(DeltaT)*norm[ncount]
    ncount<-ncount+1
    sim_r[jcount,kcount]<-rshort
    }
}
print("forward rate")
f
print("Below is the expected interest rates over 5 years, starting with now, t=0")
mean(sim_r[1,1:numpaths])
mean(sim_r[2,1:numpaths])
mean(sim_r[3,1:numpaths])
mean(sim_r[4,1:numpaths])
mean(sim_r[5,1:numpaths])
# Bond Prices
FaceVal<-100
Coupon<-6
for (jcount in 1:numpaths){
  sim_bond[Maturity+1,jcount]<-FaceVal
  for (kcount in 1:Maturity) {
    kcount1<-Maturity-kcount+1
    kcount2<-kcount1+1
    sim_bond[kcount1,jcount]<-(sim_bond[kcount2,jcount]+Coupon)*exp(-sim_r[kcount1,jcount]*DeltaT)
  }
}

# Option Pricing
K<-100
OptT<-1
sim_opt_val<-rep(0,numpaths)
for (jcount in 1:numpaths){
  sim_opt_payoff<-max(0,sim_bond[OptT+1,jcount]-K)
  for (kcount in 1:OptT) {
    sim_opt_payoff<-sim_opt_payoff*exp(-sim_r[kcount,jcount]*DeltaT)
  }
  sim_opt_val[jcount]<-sim_opt_payoff
}
#
hist(sim_opt_val[1:numpaths])
print("Option Value")
mean(sim_opt_val[1:numpaths])
```
```{r}
numpaths<-10000
Maturity<-5
sim_r<-matrix(rep(0),nrow=Maturity, ncol=numpaths)
sim_bond<-matrix(rep(0),nrow=Maturity+1, ncol=numpaths)
jcount<-1
kcount<-1
ncount<-1
DeltaT<-1
rshort<-r1
Volatility<-0.02
alpha=1 #choose alpha, beta and volatility so that it matches the current term structure
b=0.0425
for (kcount in 1:numpaths) {
  rshort<-r1
  sim_r[1,kcount]<-rshort
  for(jcount in 2:5){
    rshort<-exp(-alpha*DeltaT)*rshort+b*(1-exp(-alpha*DeltaT))+Volatility*sqrt((0.5/alpha))*(1-exp(-2*alpha*DeltaT))*norm[ncount]
    ncount<-ncount+1
    sim_r[jcount,kcount]<-rshort
    }
}
print("forward rate")
f
print("Below is the expected interest rates over 5 years, starting with now, t=0")
mean(sim_r[1,1:numpaths])
mean(sim_r[2,1:numpaths])
mean(sim_r[3,1:numpaths])
mean(sim_r[4,1:numpaths])
mean(sim_r[5,1:numpaths])

# Bond Prices
FaceVal<-100
Coupon<-6
for (jcount in 1:numpaths){
  sim_bond[Maturity+1,jcount]<-FaceVal
  for (kcount in 1:Maturity) {
    kcount1<-Maturity-kcount+1
    kcount2<-kcount1+1
    sim_bond[kcount1,jcount]<-(sim_bond[kcount2,jcount]+Coupon)*exp(-sim_r[kcount1,jcount]*DeltaT)
  }
}


# Option Pricing
K<-100
OptT<-1
sim_opt_val<-rep(0,numpaths)
for (jcount in 1:numpaths){
  sim_opt_payoff<-max(0,sim_bond[OptT+1,jcount]-K)
  for (kcount in 1:OptT) {
    sim_opt_payoff<-sim_opt_payoff*exp(-sim_r[kcount,jcount]*DeltaT)
  }
  sim_opt_val[jcount]<-sim_opt_payoff
}
#
hist(sim_opt_val[1:numpaths])
print("Option Value")
mean(sim_opt_val[1:numpaths])
```




